version: "3"
services:
  nodestatus:
    build: .
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ../:/aleph-nodestatus
      - ../logs:/logs
    command: /bin/bash -c "service cron start && echo \"*/10 * * * * nodestatus-distribute -v >> /logs/nodestatus.log\" | crontab - && /bin/sh"
